# lightning.pytorch==2.1.2
seed_everything: 42
data:  # These need to be changed
  train_chip_dir: data/cvpr/ny/train/chips/
  train_label_dir: data/cvpr/ny/train/labels/
  val_chip_dir: data/cvpr/ny/val/chips/
  val_label_dir: data/cvpr/ny/val/labels/
  metadata_path: configs/metadata.yaml
  batch_size: 16
  num_workers: 8
  platform: hls  #TODO what do I set this to?
model:
  num_classes: 110
  ckpt_path: checkpoints/clay-v1.5.ckpt
  lr: 1e-5
  wd: 0.05
  b1: 0.9
  b2: 0.95
trainer:
  accelerator: auto
  strategy: ddp
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  log_every_n_steps: 5
  max_epochs: 100
  accumulate_grad_batches: 1
  default_root_dir: checkpoints/segment
  fast_dev_run: False
  num_sanity_val_steps: 0
  logger:  # either make an account and set it up or remove the whole logger section
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        entity: developmentseed
        project: clay-segment
        group: v1.5
        log_model: false
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/segment
        auto_insert_metric_name: False
        filename: sc-county-lulc-segment_epoch-{epoch:02d}_val-iou-{val/iou:.4f} #TODO should I rename this?
        monitor: val/iou
        mode: max
        save_last: True
        save_top_k: 2
        save_weights_only: True
        verbose: True
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor  # remove if I remove the logger
      init_args:
        logging_interval: step
  plugins:
    - class_path: lightning.pytorch.plugins.io.AsyncCheckpointIO
